# Generated by Django 3.1 on 2020-08-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
